name: Override backstop

inputs:
  deployed_url:
    description: Vercel reference url without https://
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: Update to vercel deployed branch version
      run: |
        sed -i "s/http:\/\/localhost:3000/https:\/\/${{ inputs.deployed_url }}/g" backstop.json
        sed -i "s/localhost/.${{ inputs.deployed_url }}/g" backstop.json
        sed -i "s/bitmaps_local_reference/bitmaps_reference/" backstop.json
        sed -i "s/bitmaps_local_test/bitmaps_test/" backstop.json
        cat backstop.json
      shell: bash
