name: Reusable approval
inputs:
  deployed_url:
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: ⎔ Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: "npm"
        registry-url: https://npm.pkg.github.com/

    - name: Cache dependencies
      id: cache
      uses: actions/cache@v4
      with:
        path: |
          ./node_modules
        key: modules-node-${{ hashFiles('package-lock.json') }}

    - name: 📥 Download deps
      shell: bash
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Override Backstop
      uses: ./.github/actions/backstop-override
      with:
        deployed_url: ${{ inputs.deployed_url }}

    - name: ✅ Verify deployment and update branch
      shell: bash
      run: |
        URL=${{ inputs.deployed_url }}
        chmod a+x ./.github/scripts/deployment-check.sh && ./.github/scripts/deployment-check.sh https://${URL//\//\\/}

    - name: 📸 Run a test to generate snapshot
      shell: bash
      continue-on-error: true
      run: npm run backstop:test

    - name: 💽 Create an approved snapshot
      shell: bash
      run: npm run backstop:approve
