name: Reusable approval
inputs:
  deployed_url:
    required: true
    type: string

runs:
  using: "composite"

  steps:
    - name: ⎔ Setup node
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node }}
        cache: "npm"

    - name: 📥 Download deps
      run: npm ci --ignore-scripts
      env:
        NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

    - name: Override Backstop
      uses: ./.github/actions/backstop-override
      with:
        deployed_url: ${{ inputs.deployed_url }}

    - name: ✅ Verify deployment and update branch
      run: |
        URL=${{ inputs.deployed_url }}
        chmod a+x ./.github/scripts/deployment-check.sh && ./.github/scripts/deployment-check.sh https://${URL//\//\\/}
      shell: bash

    - name: 📸 Run a test to generate snapshot
      shell: bash
      continue-on-error: true
      run: npm run backstop:test

    - name: 💽 Create an approved snapshot
      shell: bash
      run: npm run backstop:approve
