name: Create Approved Snapshot By File

on:
  workflow_dispatch:
    inputs:
      branch:
        description: Branchname to execute
        default: ${{ github.ref_name }}
  workflow_call:
    inputs:
      branch:
        description: Branchname to execute
        default: ${{ github.ref_name }}

jobs:
  auto_approve:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.inputs.branch }}

      - name: Approve Backstop
        uses: ./.github/actions/approve
        with:
          deployed_url: ${{ github.inputs.branch }}
          branch: ${{ github.inputs.branch }}
