name: Create Approved Snapshot By File

on:
  workflow_dispatch:
    inputs:
      vercel_deployed_url:
        description: Vercel reference url without https://
  pull_request:
    types:
      - synchronize
    paths:
      - "backstopjs.approve"

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0
  approve:
    uses: ./.github/workflows/reusable-approval.yml
    with:
      deployed_url: ${{ github.head_ref }}
      branch: ${{ github.head_ref }}
    secret:
      PAT: ${{ secrets.PAT }}
