name: Create Approved Snapshot By File

on:
  pull_request:
    types:
      - synchronize
    paths:
      - "backstopjs.approve"

jobs:
  approve:
    uses: ./.github/workflows/reusable-approval.yml
    with:
      deployed_url: ${{ github.head_ref }}
      branch: ${{ github.head_ref }}
    secrets:
      PAT: ${{ secrets.PAT }}
