name: Create Approved Snapshot Manually

on:
  workflow_dispatch:
    inputs:
      vercel_deployed_url:
        description: Vercel reference url without https://

jobs:
  cancel:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: Manual Approve Backstop
        uses: ./.github/workflows/reusable-approval.yml
        if: steps.autoapproval.outputs.BACKSTOP_APPROVED == 'true'
        with:
          deployed_url: ${{ github.ref_name }}
          branch: ${{ github.ref_name }}
        secret:
          PAT: ${{ secrets.PAT }}
