name: Report merged result on master

on:
  push:
    branches:
      - master

jobs:
  # Re-run push
  merge:
    permissions:
      pull-requests: write
    uses: ./.github/workflows/push.yml
    with:
      push_code_coverage: true
