name: Main code on pull request

on:
  pull_request: {}

jobs:
  TaskDecider:
    name: TaskDecider
    runs-on: ubuntu-latest
    outputs:
      TO_APPROVE: ${{ steps.autoapproval.outputs.BACKSTOP_APPROVED }}
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ❓ Auto approve
        id: autoapproval
        run: |
          APPROVE_RUN_NUMBER=`cat ./backstopjs.approve`
          echo github [$GITHUB_RUN_NUMBER]
          echo approve [$APPROVE_RUN_NUMBER]
          echo
          if [ "$APPROVE_RUN_NUMBER" = "$GITHUB_RUN_NUMBER" ]; then
              echo "BACKSTOP_APPROVED=true" >> $GITHUB_OUTPUT
          else
              echo "BACKSTOP_APPROVED=false" >> $GITHUB_OUTPUT
          fi
