name: Reusable approval

on:
  workflow_call:
    inputs:
      deployed_url:
        required: true
        type: string
      branch:
        required: true
        type: string

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Set domain
        id: domain
        shell: bash
        run: |
          url="walcron-git-${{ github.event.inputs.branch }}-walcoorperation.vercel.app"
          echo "URL=${url//\//\\/}" >> $GITHUB_OUTPUT
          echo "URL set to ${url}"

      - name: Override Backstop
        uses: ./.github/workflows/reusable-override-backstop.yml
        with:
          deployed_url: ${{ steps.domain.outputs.URL }}

      - name: ⬆️ Run a test to generate snapshot
        continue-on-error: true
        run: npm run backstop:test

      - name: ⬆️ Create an approved snapshot
        run: npm run backstop:approve

      - name: 💼 Auto commit on approved backstop
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update backstop with auto approval
          file_pattern: "backstop_data/bitmaps_reference/*.png"
