name: Reusable approval

on:
  workflow_dispatch:
    inputs:
      deployed_url:
        description: Vercel reference url without https://
        required: true
        type: string
      branch:
        required: true
        type: string
    secrets:
      PAT:
        required: true

jobs:
  approver:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.event.inputs.branch }}

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Set domain
        id: domain
        shell: bash
        run: |
          url="walcron-git-${{ github.event.inputs.branch }}-walcoorperation.vercel.app"
          echo "URL=${url//\//\\/}" >> $GITHUB_OUTPUT
          echo "URL set to ${url}"

      - name: Update to vercel deployed branch version
        run: |
          sed -i "s/http:\/\/localhost:3000/https:\/\/${{ steps.domain.outputs.URL }}/g" backstop.json
          sed -i "s/localhost/.${{ steps.domain.outputs.URL }}/g" backstop.json
          sed -i "s/bitmaps_local_reference/bitmaps_reference/" backstop.json
          sed -i "s/bitmaps_local_test/bitmaps_test/" backstop.json
          cat backstop.json
        shell: bash

      - name: ⬆️ Run a test to generate snapshot
        continue-on-error: true
        run: npm run backstop:test

      - name: ⬆️ Create an approved snapshot
        run: npm run backstop:approve

      - name: 💼 Auto commit on approved backstop
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update backstop with auto approval
          file_pattern: "backstop_data/bitmaps_reference/*.png"
