name: Create Snapshot

on:
  workflow_dispatch:
    inputs:
      vercel_deployed_url:
        description: Vercel reference url
        required: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Update to vercel deployed branch version
        run: |
          sed -i "s/http:\/\/localhost:3000/${{ github.event.inputs.vercel_deployed_url }}/g" backstop.json
          cat backstop.json
        shell: bash

      - name: ⬆️ Create an approved snapshot
        run: npm run backstop:approve

      - name: Upload approved snapshot artifacts
        uses: actions/upload-artifact@v3
        with:
          name: backstop-artifact
          path: backstop_data/

      - name: Verify Backstopjs snapshot is valid
        with:
          name: backstop-artifact
          path: backstop_data/
