name: Create Approved Snapshot

on:
  workflow_dispatch:
    inputs:
      vercel_deployed_url:
        description: Vercel reference url without https://
  pull_request:
    types:
      - synchronize
    paths:
      - "backstopjs.approve"

jobs:
  approver:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          ref: ${{ github.ref_name }}

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}
          cache: "npm"

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Determine domain
        id: domain
        shell: bash
        run: |
          APPROVE_RUN_NUMBER=`cat ./backstopjs.approve`
          echo github [$GITHUB_RUN_NUMBER]
          echo approve [$APPROVE_RUN_NUMBER]
          echo "url: ${{ github.event.inputs.vercel_deployed_url }}"
          echo "branch: ${{ github.ref_name }}, ${{ github.head_ref }}"
          url=""
          echo
          if [ "$APPROVE_RUN_NUMBER" = "$GITHUB_RUN_NUMBER" ]; then
            url="walcron-git-${{ github.head_ref }}-walcoorperation.vercel.app"
          else
            if [ "${{ github.event.inputs.vercel_deployed_url }}" = "" ]; then
              url="walcron-git-${{ github.ref_name }}-walcoorperation.vercel.app"
            else
              url=${{ github.event.inputs.vercel_deployed_url }}
            fi
          fi
          echo "URL=${url//\//\\/}" >> $GITHUB_OUTPUT
          echo "URL set to ${url}"

      - name: Update to vercel deployed branch version
        run: |
          sed -i "s/http:\/\/localhost:3000/https:\/\/${{ steps.domain.outputs.URL }}/g" backstop.json
          sed -i "s/localhost/.${{ steps.domain.outputs.URL }}/g" backstop.json
          sed -i "s/bitmaps_local_reference/bitmaps_reference/" backstop.json
          sed -i "s/bitmaps_local_test/bitmaps_test/" backstop.json
          cat backstop.json
        shell: bash

      - name: ⬆️ Run a test to generate snapshot
        continue-on-error: true
        run: npm run backstop:test

      - name: ⬆️ Create an approved snapshot
        run: npm run backstop:approve

      - name: 💼 Auto commit on approved backstop
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update backstop with auto approval
          file_pattern: "backstop_data/bitmaps_reference/*.png"
