name: snapshot
on: workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Just to say hi
        run: initially this was to take snapshot, but to checkout deps again, it's better not
        shell: bash
