name: snapshot
on: workflow_call
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: ⬆️ Run page rendering check
        continue-on-error: true
        run: npm run backstop:test:deploy

      - uses: actions/upload-artifact@v3
        with:
          name: backstop-artifact
          path: backstop_data/

      - name: Backstopjs snapshot is valid
        run: echo $PWD && ./.github/scripts/snapshot-check.sh
        shell: bash
