name: Create Approved Snapshot

on:
  workflow_dispatch:
    inputs:
      vercel_deployed_url:
        description: Vercel reference url

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: 🛑 Cancel Previous Runs
        uses: styfle/cancel-workflow-action@0.9.0

      - name: ⬇️ Checkout repo
        uses: actions/checkout@v2
        with:
          ref: ${{ github.head_ref }}

      - name: ⎔ Setup node
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node }}

      - name: 📥 Download deps
        uses: bahmutov/npm-install@v1
        with:
          useLockFile: false

      - name: Determine domain
        id: domain
        shell: bash
        run: |
          echo "entered url: ${{ github.event.inputs.vercel_deployed_url }}"
          url=""
          if [ "${{ github.event.inputs.vercel_deployed_url }}" = "" ]; then
            url="https://walcron-git-${GITHUB_HEAD_REF//\//\\/}-walcoorperation.vercel.app"
          else
            url=${{ github.event.inputs.vercel_deployed_url }}
          fi
          echo "URL=${url}" >> $GITHUB_OUTPUT
          echo "URL set to ${url}"

      - name: Update to vercel deployed branch version
        run: |
          sed -i "s/http:\/\/localhost:3000/${{ steps.domain.outputs.URL }}/g" backstop.json
          sed -i "s/bitmaps_local_reference/bitmaps_reference/" backstop.json
          sed -i "s/bitmaps_local_test/bitmaps_test/" backstop.json
          cat backstop.json
        shell: bash

      - name: ⬆️ Run a test to generate snapshot
        continue-on-error: true
        run: npm run backstop:test

      - name: ⬆️ Create an approved snapshot
        run: npm run backstop:approve

      - name: 💼 Auto commit on approved backstop
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update backstop with auto approval
          file_pattern: "backstop_data/bitmaps_reference/*.png"
